# Generated by Django 4.0.6 on 2022-08-08 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), default=['test'], size=8),
            preserve_default=False,
        ),
    ]
