# Generated by Django 4.0.6 on 2022-08-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active_alter_user_is_staff'),
        ('accounts', '0012_role_hotel'),
    ]

    operations = [
    ]
