# Generated by Django 4.0.6 on 2022-08-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_hotel'),
        ('accounts', '0014_alter_user_is_active_alter_user_is_staff'),
    ]

    operations = [
    ]
