# Generated by Django 4.0.6 on 2022-08-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_items_disc_price_alter_items_price'),
        ('main_app', '0012_standard_hotel'),
    ]

    operations = [
    ]
