# Generated by Django 4.0.6 on 2022-08-08 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_standard_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='menu_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=8),
        ),
    ]
