# Generated by Django 4.0.6 on 2022-08-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20220810_1242'),
        ('main_app', '0013_room_menu_array'),
    ]

    operations = [
    ]
