# Generated by Django 4.0.6 on 2022-08-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_hotem_guests_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='general_manager',
        ),
    ]
