# Generated by Django 4.0.6 on 2022-08-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_hotel_general_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='general_manager',
            field=models.BooleanField(default=False),
        ),
    ]
