# Generated by Django 4.0.6 on 2022-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_hotel_general_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='payment_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
