# Generated by Django 4.0.6 on 2022-08-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_0013_merge_20220810_1242_0013_room_menu_array'),
        ('main_app', '0020_hotel_payment_status'),
    ]

    operations = [
    ]
