# Generated by Django 4.0.6 on 2022-09-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0005_alter_smily_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smily',
            name='mood',
        ),
    ]
