# Generated by Django 4.0.6 on 2022-09-08 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0007_smily_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smily',
            name='mood',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=8),
        ),
    ]
