# Generated by Django 4.0.6 on 2022-08-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_room_menu_array'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='affiliate',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='company',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_till',
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.hotel'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_use_per_user',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_type',
            field=models.CharField(blank=True, choices=[('unlimited time for all users', 'Unlimited time for all users'), ('once for new user for first order', 'Once for new user for first order'), ('once per user', 'Once per user'), ('define custom limit per user', 'Define custom limit per user')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed amount discount', 'Fixed Amount Discount'), ('percentage discount', 'Percentage Discount')], max_length=100, null=True),
        ),
    ]
