# Generated by Django 4.0.6 on 2022-08-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_coupon_affiliate_remove_coupon_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='menu',
        ),
    ]
