# Generated by Django 4.0.6 on 2022-08-17 11:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_coupon_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='menu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
    ]
