# Generated by Django 4.0.6 on 2022-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_coupon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
